---
# yamllint disable rule:truthy

name: 'Yamllint'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Run yamllint'
        uses: ibiqlik/action-yamllint@v1.0.0

...
